language: go

dist: trusty
sudo: false

install:
 - go get github.com/kardianos/govendor
 - govendor get github.com/spf13/hugo

script:
 - hugo --cleanDestinationDir -s source/ -d ../docs --theme=kiss --enableGitInfo
