language: go

dist: trusty
sudo: false

install:
 - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
 - tar xvf hugo_0.48_Linux-64bit.tar.gz
 - mv hugo $GOPATH/bin/
 - rm README.md LICENSE

script:
 - hugo --cleanDestinationDir -s source/ -d ../docs --theme=kiss --enableGitInfo