language: go

dist: trusty
sudo: false

install:
 - wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.tar.gz
 - tar xvf hugo_0.37.1_Linux-64bit.tar.gz
 - mv hugo $GOPATH/bin/
 - rm README.md LICENSE.md

script:
 - hugo --cleanDestinationDir -s source/ -d ../docs --theme=kips --enableGitInfo
