baseurl: "https://lucynaess.github.io/disconnected/"
languageCode: "en-us"
title: "Disconnected"
copyright: "Copyright Lucrèce Skylar Næss 2018"
enableRobotsTXT: true

params:
        assets:
                customCSS: ["css/custom.css"]
        info:
                enableScoial: true
                poweredBy: true
                homeTitle: "Disconnected"
                related: true
        rss:
                includeContent: true
                authorName: "Lucrèce Skylar Næss"
                authorEmail: "lucrecenaess@airmail.cc"
        social:
                twitter: "lucynaess"
                github: "lucynaess"
                email: "lucrecenaess@airmail.cc"
                rss: "index.xml"
                config:
                        platforms: ["github", "twitter", "email", "rss"]
        AuthorName: "Lucrèce Skylar Næss"
        description: "A blog"
        enableGitinfo: true
        preserveTaxonomyNames: true

taxonomies:
        tag: "tags"
        category: "categories"
        series: "series"
