baseurl: "https://lucynaess.github.io/disconnected/"
languageCode: "en-us"
title: "Disconnected"
theme: "kiss"
copyright: "Copyright Lucrèce Skylar Næss 2017."
enableRobotsTXT: true

author:
        name: "Lucrèce Skylar Næss"
        email: "lucrecenaess@airmail.cc"


params:
        info:
                enableScoial: true
                poweredby: true
                homeTitle: "Disconnected"
        social:
                twitter: "@lucynaess"
                github: "lucynaess"
                instagram: "lucynaess"
                email: "lucrecenaess@airmail.cc"
        opengraph:
                twitter:
                        page: "@lucynaess"
        AuthorName: "Lucrèce Skylar Næss"
        description: "A blog"
        Summary: false
        Content: false
        enableGitinfo: true
        preserveTaxonomyNames: true

taxonomies:
        tag: "tags"
        category: "categories"
        series: "series"
